--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Carrinhos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Carrinhos" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "DataFinalizacao" timestamp with time zone,
    "Total" numeric(18,2) NOT NULL,
    "Ativo" boolean NOT NULL
);


ALTER TABLE public."Carrinhos" OWNER TO postgres;

--
-- Name: Carrinhos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Carrinhos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Carrinhos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categorias" (
    "Id" integer NOT NULL,
    "Nome" character varying(100) NOT NULL
);


ALTER TABLE public."Categorias" OWNER TO postgres;

--
-- Name: Categorias_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categorias" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categorias_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Enderecos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Enderecos" (
    "Id" integer NOT NULL,
    "Cep" character varying(8) NOT NULL,
    "Logradouro" character varying(200) NOT NULL,
    "Numero" character varying(10) NOT NULL,
    "Complemento" character varying(100),
    "Referencia" character varying(100),
    "Bairro" character varying(100) NOT NULL,
    "Cidade" character varying(100) NOT NULL,
    "Estado" character varying(2) NOT NULL,
    "TipoEndereco" text,
    "Ativo" boolean NOT NULL,
    "UserId" integer NOT NULL,
    "Identificacao" character varying(50) DEFAULT ''::character varying
);


ALTER TABLE public."Enderecos" OWNER TO postgres;

--
-- Name: Enderecos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Enderecos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Enderecos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Favoritos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Favoritos" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ProdutoId" integer NOT NULL
);


ALTER TABLE public."Favoritos" OWNER TO postgres;

--
-- Name: Favoritos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Favoritos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Favoritos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ItemPedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ItemPedido" (
    "Id" integer NOT NULL,
    "PedidoId" integer NOT NULL,
    "ProdutoId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "PrecoUnitario" numeric(18,2) NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL
);


ALTER TABLE public."ItemPedido" OWNER TO postgres;

--
-- Name: ItemPedido_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ItemPedido" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ItemPedido_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ItensCarrinho; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ItensCarrinho" (
    "Id" integer NOT NULL,
    "CarrinhoId" integer NOT NULL,
    "ProdutoId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "PrecoUnitario" numeric(18,2) NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "StatusItem" text NOT NULL
);


ALTER TABLE public."ItensCarrinho" OWNER TO postgres;

--
-- Name: ItensCarrinho_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ItensCarrinho" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ItensCarrinho_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Pedidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Pedidos" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DataPedido" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "EnderecoId" integer
);


ALTER TABLE public."Pedidos" OWNER TO postgres;

--
-- Name: Pedidos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Pedidos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pedidos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProdutoImagens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProdutoImagens" (
    "Id" integer NOT NULL,
    "Url" character varying(500) NOT NULL,
    "Titulo" character varying(255),
    "Ordem" integer NOT NULL,
    "ProdutoId" integer NOT NULL
);


ALTER TABLE public."ProdutoImagens" OWNER TO postgres;

--
-- Name: ProdutoImagens_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProdutoImagens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProdutoImagens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Produtos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Produtos" (
    "Id" integer NOT NULL,
    "Nome" character varying(100) NOT NULL,
    "Slug" character varying(150),
    "Descricao" character varying(900),
    "Preco" numeric(18,2) NOT NULL,
    "CategoriaId" integer NOT NULL,
    "PrecoAntigo" numeric(18,2),
    "Marca" character varying(100) DEFAULT ''::character varying NOT NULL,
    "Quantidade" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Produtos" OWNER TO postgres;

--
-- Name: Produtos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Produtos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Produtos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TrocasEmail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TrocasEmail" (
    "Id" integer NOT NULL,
    "EmailAtual" text NOT NULL,
    "NovoEmail" text NOT NULL,
    "Codigo" text NOT NULL,
    "Expiracao" timestamp with time zone NOT NULL,
    "Utilizado" boolean NOT NULL
);


ALTER TABLE public."TrocasEmail" OWNER TO postgres;

--
-- Name: TrocasEmail_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TrocasEmail" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TrocasEmail_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Nome" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Senha" character varying(100) NOT NULL,
    "Telefone" character varying(20),
    "Ativo" boolean NOT NULL,
    "Role" character varying(20),
    "Cpf" text DEFAULT ''::text NOT NULL,
    "DataNascimento" date DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "Genero" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Carrinhos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Carrinhos" ("Id", "UserId", "DataCriacao", "DataFinalizacao", "Total", "Ativo") FROM stdin;
\.


--
-- Data for Name: Categorias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categorias" ("Id", "Nome") FROM stdin;
1	EletrÃ´nicos
4	cadeira-Gamer
5	celular-smartphone
6	Computadores
7	monitor
\.


--
-- Data for Name: Enderecos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Enderecos" ("Id", "Cep", "Logradouro", "Numero", "Complemento", "Referencia", "Bairro", "Cidade", "Estado", "TipoEndereco", "Ativo", "UserId", "Identificacao") FROM stdin;
\.


--
-- Data for Name: Favoritos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Favoritos" ("Id", "UserId", "ProdutoId") FROM stdin;
\.


--
-- Data for Name: ItemPedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ItemPedido" ("Id", "PedidoId", "ProdutoId", "Quantidade", "PrecoUnitario", "Subtotal") FROM stdin;
\.


--
-- Data for Name: ItensCarrinho; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ItensCarrinho" ("Id", "CarrinhoId", "ProdutoId", "Quantidade", "PrecoUnitario", "Subtotal", "StatusItem") FROM stdin;
\.


--
-- Data for Name: Pedidos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Pedidos" ("Id", "UserId", "DataPedido", "Status", "EnderecoId") FROM stdin;
\.


--
-- Data for Name: ProdutoImagens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProdutoImagens" ("Id", "Url", "Titulo", "Ordem", "ProdutoId") FROM stdin;
1	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F1%2Ff0486430-d879-4cf6-99f3-449ed8d16905_.webp?alt=media	Xiaomi Redmin Note 14 -2.webp	0	1
2	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F2%2F78cccf0a-2f00-4779-9c9e-042b78bcdc09_.webp?alt=media	cadeira-gamer1.webp	0	2
3	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F2%2Fedec816f-ba91-4f85-a389-eec5d5b22624_.webp?alt=media	cadeira-gamer2.webp	1	2
4	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F3%2F58ed87ef-7984-4554-8c31-7a6236b5ac45_.jpg?alt=media	ThunderX3 EC1 RGB Black Edition-1.jpg	0	3
5	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F3%2F88c52128-f92f-4755-a901-39deec08d8c0_.jpg?alt=media	ThunderX3 EC1 RGB Black Edition-2.jpg	1	3
6	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F3%2Fcdbb83c3-795d-4fd0-96f3-403c6f3f0096_.jpg?alt=media	ThunderX3 EC1 RGB Black Edition-3.jpg	2	3
7	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F3%2F785c6992-cb74-4bd4-837c-ffc4a6eb172a_.jpg?alt=media	ThunderX3 EC1 RGB Black Edition-4.jpg	3	3
8	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F3%2Fcda617e4-fff9-40da-8463-745fd3911b64_.webp?alt=media	ThunderX3 EC1 RGB Black Edition-5.webp	4	3
9	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F4%2Fd54bc598-88c7-40b6-9554-e7da8b73bda8_.jpg?alt=media	ThunderX3 BC3 Camo Blue-1.jpg	0	4
10	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F4%2F346236ad-23f2-47bc-afe9-0612a53a3820_.jpg?alt=media	ThunderX3 BC3 Camo Blue-2.jpg	1	4
11	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F4%2F48e140c3-924c-4594-986d-0796a8b9cd56_.jpg?alt=media	ThunderX3 BC3 Camo Blue-3.jpg	2	4
12	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F4%2Ffa34ddec-df7a-47b8-af39-896fee246eae_.jpg?alt=media	ThunderX3 BC3 Camo Blue-4.jpg	3	4
13	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F4%2Fb09dcd19-3d7f-4269-ae57-af9ecd2a891c_.webp?alt=media	ThunderX3 BC3 Camo Blue-5.webp	4	4
14	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F5%2Fdf92cdc8-2554-4750-abf8-c7349370654e_.jpg?alt=media	Cadeira Gamer ThunderX3 YC3 PretoVermelho,-1.jpg	0	5
15	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F5%2Fd7713a19-46c9-48b3-bbc4-281cf4ef61f1_.jpg?alt=media	Cadeira Gamer ThunderX3 YC3 PretoVermelho,-2.jpg	1	5
16	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F5%2F4ae2472f-a3df-4048-8d4f-a78ffcf6c0bd_.jpg?alt=media	Cadeira Gamer ThunderX3 YC3 PretoVermelho,-3.jpg	2	5
17	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F5%2F72cbe03a-b898-43d3-8736-37c3e35dbdc0_.jpg?alt=media	Cadeira Gamer ThunderX3 YC3 PretoVermelho,-4.jpg	3	5
18	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F5%2F6d7416c9-7cd2-4469-8169-39d47558bcf3_.jpg?alt=media	Cadeira Gamer ThunderX3 YC3 PretoVermelho,-5.jpg	4	5
19	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F6%2F5376be13-4de2-4bec-ad97-69ad738db1cf_.webp?alt=media	Cadeira Gamer ThunderX3 TC5 Max Preta-1.webp	0	6
20	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F6%2F8d417229-9800-4870-996e-18af846ad860_.webp?alt=media	Cadeira Gamer ThunderX3 TC5 Max Preta-2.webp	1	6
21	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F6%2F049ff1d9-a088-42e8-b3c9-c9c70ada7496_.webp?alt=media	Cadeira Gamer ThunderX3 TC5 Max Preta-3.webp	2	6
22	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F6%2F8b50202a-c531-4305-8930-a5ce96732acb_.webp?alt=media	Cadeira Gamer ThunderX3 TC5 Max Preta-4.webp	3	6
23	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F6%2Fa8bff89d-022b-4b73-b5e9-92ecc64d5803_.webp?alt=media	Cadeira Gamer ThunderX3 TC5 Max Preta-5.webp	4	6
24	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F6%2F653cb778-5020-4bb8-b3b6-5f3ef35723e3_.webp?alt=media	Cadeira Gamer ThunderX3 TC5 Max Preta-6.webp	5	6
25	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F7%2F729a42aa-cd44-497d-89af-bb3111d21683_.png?alt=media	DXRacer Formula Series Preta-1.png	0	7
26	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F7%2F90fa7c8c-99ee-47bb-82f6-abd0e07a1807_.png?alt=media	DXRacer Formula Series Preta-2.png	1	7
27	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F7%2F9e84a453-1052-49f7-882c-043b3f29e4ea_.png?alt=media	DXRacer Formula Series Preta-3.png	2	7
28	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F7%2Ff07f60bf-3be9-4f01-bab7-7366c9cc9094_.png?alt=media	DXRacer Formula Series Preta-4.png	3	7
29	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F7%2F64ffa76d-58a0-4dfd-adf0-3e3e4c3909c3_.png?alt=media	DXRacer Formula Series Preta-5.png	4	7
30	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F7%2F2acc85f4-8531-42b2-83e0-c23cb1f80e2b_.png?alt=media	DXRacer Formula Series Preta-6.png	5	7
31	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F8%2Fd7dbfc26-ff3d-4a6a-8dfe-31f634ed433d_.png?alt=media	DXRacer Racing Series Branca e-1.png	0	8
32	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F8%2F11539f4c-23f7-475c-9fae-d2e64c1b965a_.png?alt=media	DXRacer Racing Series Branca e-2.png	1	8
33	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F8%2F7038b015-c2f5-4d18-8f0c-e789e07c6cc2_.png?alt=media	DXRacer Racing Series Branca e-3.png	2	8
34	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F8%2Fc1e5dbc1-92ec-4190-9419-d36c0e0c5886_.png?alt=media	DXRacer Racing Series Branca e-4.png	3	8
72	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F16%2Fc2572e6b-d117-475c-9193-d02d9e46399c_.jpg?alt=media	24G2-BK3.jpg	2	16
35	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F8%2F5d1be2e6-2b12-4cb6-a150-e6b2a12014dd_.png?alt=media	52d56a43-3c42-4144-a721-0034d1d9ae66-3.png	4	8
36	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F9%2F73544ce8-e5c8-4b54-b878-b7914daec964_.jpg?alt=media	616k4FTcXVL._AC_SX569_.jpg	0	9
37	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F9%2F970c5616-62dc-4815-8511-d19794ec843f_.jpg?alt=media	51yVB3jXttL._AC_SX679_.jpg	1	9
38	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F9%2F944fb041-7bae-4f1b-8aff-c2d82fb275be_.jpg?alt=media	61enhZaeMXL._AC_SX679_.jpg	2	9
39	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F9%2F774f87ea-5f2f-40ec-beab-f2dfb8da33e1_.jpg?alt=media	51VEvoHr-IL._AC_SX679_.jpg	3	9
40	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F10%2F7eb8c736-02c8-47db-9f18-7f1f3fef9518_.jpg?alt=media	Samsung Odyssey G5 27 144Hz Curvo QHD-1.jpg	0	10
41	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F10%2F7f2c6bf7-bc62-402a-9e91-428d48a3cc95_.jpg?alt=media	Samsung Odyssey G5 27 144Hz Curvo QHD-2.jpg	1	10
42	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F10%2F0ca64f5a-956b-4436-a0eb-e6c5311d33a7_.jpg?alt=media	Samsung Odyssey G5 27 144Hz Curvo QHD-3.jpg	2	10
43	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F10%2F8d1cd477-03ca-4240-af2f-e86b0ae74ae4_.jpg?alt=media	Samsung Odyssey G5 27 144Hz Curvo QHD-4.jpg	3	10
44	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F10%2F78a261be-260b-4e08-a080-ac33977feb97_.jpg?alt=media	Samsung Odyssey G5 27 144Hz Curvo QHD-5.jpg	4	10
45	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F11%2F6e062cbb-a2a7-437e-a5af-54f1cac59fde_.webp?alt=media	Monitor-Gamer-Samsung-T350-1.webp	0	11
46	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F11%2F486228fd-980a-483a-b2fa-0b56f8de125f_.webp?alt=media	Monitor-Gamer-Samsung-T350-3.webp	1	11
47	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F11%2Fa1712f87-89be-4746-860b-887d42065178_.webp?alt=media	Monitor-Gamer-Samsung-T350-4.webp	2	11
48	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F11%2F558d7866-dd2c-4752-b8c8-a98bb862c0aa_.webp?alt=media	Monitor-Gamer-Samsung-T350-5.webp	3	11
49	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F12%2Fa8197517-53d2-4abc-89b7-c20c8d8d3e92_.jpg?alt=media	81e66ug3aRL._AC_SL1500_.jpg	0	12
50	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F12%2F258ef926-b1ed-483b-bdd2-0e469ba72f8c_.jpg?alt=media	81iN4ZWzqrL._AC_SL1500_.jpg	1	12
51	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F12%2F20987e25-8831-481a-8e8f-58b141e0edb6_.jpg?alt=media	81N5Sd0oDvS._AC_SL1500_.jpg	2	12
52	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F12%2Fd0b1195f-0277-49b8-a83b-521ffe083fc1_.jpg?alt=media	81Ol5CYCdwL._AC_SL1500_.jpg	3	12
53	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F12%2Fe1e0a5b4-42e6-4ffd-a7d4-2b187fe9c1ef_.jpg?alt=media	81wfdDTIjHS._AC_.jpg	4	12
54	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F13%2F66ecdefd-ceeb-4748-96af-5bb4aa0dcf4f_.jpeg?alt=media	thum-1600x1062 (4).jpeg	0	13
55	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F13%2Faf9b6c58-74ee-4c4d-9217-7c4660eb1fd0_.jpeg?alt=media	thum-1600x1062 (1).jpeg	1	13
56	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F13%2F24c1bf31-0dd9-49b4-bafc-ad17a221d9db_.jpeg?alt=media	thum-1600x1062 (2).jpeg	2	13
57	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F13%2F9012de50-03ce-4560-bfc1-60d531fda7e3_.jpeg?alt=media	thum-1600x1062 (3).jpeg	3	13
58	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F13%2F8e2303eb-a2dd-44cb-a2ef-dfa261e4c033_.jpeg?alt=media	thum-1600x1062.jpeg	4	13
59	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F14%2Ff36ca46e-6e62-4f45-a695-b0600fa24c34_.jpg?alt=media	DZ_02.jpg	0	14
60	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F14%2F2dd99a6c-e33b-4af5-9f0e-fb8a7495df7a_.jpg?alt=media	DZ_07.jpg	1	14
61	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F14%2F823547ae-896a-45e9-bb62-61fc62bcf38f_.jpg?alt=media	DZ_08.jpg	2	14
62	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F14%2Feb31a73e-d7da-477b-aafd-f3ea05d17d17_.jpg?alt=media	DZ_09.jpg	3	14
63	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F14%2F69e0e039-9da5-4153-885a-b46a85e3cd04_.jpg?alt=media	DZ_10.jpg	4	14
64	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F14%2F95fe6b7b-6e85-430b-8d46-55408839fcd2_.jpg?alt=media	DZ-001.jpg	5	14
65	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F15%2F0817eece-0892-4583-ace2-559c3d98ba22_.jpg?alt=media	large02.jpg	0	15
66	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F15%2F7eb8a3a9-ece6-4955-8b10-2d4fd31fb180_.jpg?alt=media	large08.jpg	1	15
67	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F15%2F3348cea7-1406-4ac5-8b8f-af6c50d4cc2d_.jpg?alt=media	GNB-mobile (1).jpg	2	15
68	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F15%2F35d92f1a-5bf2-4aa2-b74e-5d084c4ce591_.jpg?alt=media	GNB-mobile.jpg	3	15
69	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F15%2F305c01a7-4c05-4f75-addc-65d13c98be2d_.jpg?alt=media	large04.jpg	4	15
70	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F16%2F719cfcdc-67d1-4059-a921-55649eadf39f_.png?alt=media	AOCG_G2_FV_FW_IPS_FRONT-large.png	0	16
71	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F16%2F25cdae64-ce48-462d-a9a0-e845c6ba3a01_.jpg?alt=media	24G2-BK.jpg	1	16
73	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F16%2F5dc50ff9-b7af-431b-b4b4-1ce6358ab856_.jpg?alt=media	24G2-BK4.jpg	3	16
74	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F16%2F836b3152-4eaf-4b1d-8838-62927b6cd606_.jpg?alt=media	24G2-BK5.jpg	4	16
75	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F17%2F619dc930-6680-4ae4-80dd-1e12521e34f9_.jpg?alt=media	2_f8d3eef6-1a1c-4366-892a-3361672aac8b_5000x.jpg	0	17
76	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F17%2F5da8fe44-3890-4f9d-8eb6-9f9426e8849c_.jpg?alt=media	8_77928aee-ef48-4f28-b755-50f4b207532d_5000x.jpg	1	17
77	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F17%2F2fb09c74-7760-4d66-a056-eab47cc75639_.jpg?alt=media	7_c6856466-0d27-4a50-8ddb-bdf021876e4f_5000x.jpg	2	17
78	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F17%2F29cb5786-87ff-4ec6-bb10-46fc68a75198_.jpg?alt=media	5_75508b94-3109-4d50-a0d9-c8dcb862be57_5000x.jpg	3	17
79	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F17%2Faed5e5d2-6e8a-406c-bc13-ce68287d537c_.jpg?alt=media	3_90d48d10-c7a5-4b73-acf8-64ddbd1e892a_5000x.jpg	4	17
80	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F17%2F3dd0c06e-970f-4fa1-9bc2-0ec731da8f93_.jpg?alt=media	6_74943d56-50b1-45a1-8389-283daa953820_5000x.jpg	5	17
81	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F18%2F91496a5b-7bd4-4897-b27f-6bbbbf35f8f6_.jpg?alt=media	5xg.jpg	0	18
82	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F18%2F1b277812-e7e5-4b48-b0b1-3508af86b09f_.jpg?alt=media	83ebd093-2afb-4d24-9931-b48033acf5c2.jpg	1	18
83	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F18%2F6885e711-b591-4c3a-ac5b-4eba2323e7c8_.jpg?alt=media	30591ee8-9b18-47b5-9354-71694ae07625.jpg	2	18
84	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F18%2F82c2a555-4076-455a-84fb-f9090ae0ec04_.jpg?alt=media	b619758e-ac83-4aa0-b80e-375f3b129fdf.jpg	3	18
85	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F18%2F38596c6f-51dc-4e38-b64c-9ff6d940f370_.jpg?alt=media	4xg.jpg	4	18
86	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F18%2F2e7e512b-2e4c-4061-8e23-0f266b16a526_.jpg?alt=media	88acfe52-364a-44ff-86ea-daa05d8f0138.jpg	5	18
87	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F19%2F1a09e110-83a4-42cb-a3ca-8516aed34f64_.jpeg?alt=media	4abaaf71-25dc-4a44-9f41-ee5eb453ed23.__CR0,0,1464,600_PT0_SX1464_V1___.jpeg	0	19
88	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F19%2Fb9fae64a-aa46-4d7f-a585-333adcf48887_.jpeg?alt=media	6fbcd436-ed66-405d-935f-fe4cbf193b8b.__CR0,0,1464,600_PT0_SX1464_V1___.jpeg	1	19
89	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F19%2Fdbb4b84e-fe53-4810-bfd4-bbdacce4932a_.jpeg?alt=media	8a84eb15-fe8b-41f4-ab11-43a444aa657e.__CR0,0,1464,600_PT0_SX1464_V1___.jpeg	2	19
90	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F19%2F77f885db-9920-40d8-9aa4-d5b71949a5f9_.png?alt=media	810U1-qOOUL.png	3	19
91	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F19%2Fcc9ea3cd-39ce-4786-952d-e50f10faa01d_.jpeg?alt=media	d5c1dd31-3b15-4ae2-9a80-2be68aa466c2.__CR0,0,1464,600_PT0_SX1464_V1___.jpeg	4	19
92	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F19%2Fc78b2c7f-3c00-40ae-b7f2-61db51de1eef_.jpeg?alt=media	e03a330d-7d3f-4530-93ff-6ced9c5eb492.__CR0,0,1464,600_PT0_SX1464_V1___.jpeg	5	19
93	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F19%2Fd50cdda8-87d0-4e25-9eb3-66b3452b6a3d_.jpeg?alt=media	e96aca36-836e-4ffc-9db2-6fb414bfb554.__CR0,0,1464,600_PT0_SX1464_V1___.jpeg	6	19
94	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F20%2F2abf8206-0897-4b3a-8cc0-bf7663eca56a_.webp?alt=media	Smartphone-Xiaomi-Redmi-Note-14-256GB-8GB-RAM-6-67-AMOLED-120Hz-C-mera-108Mp-Verde_1752181183.webp	0	20
95	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F20%2F8a059f97-1c5f-4fb3-b546-c2ed2e6a9c30_.webp?alt=media	Smartphone-Xiaomi-Redmi-Note-14-256GB-8GB-RAM-6-67-AMOLED-120Hz-C-mera-108Mp-Verde_1752181184.webp	1	20
96	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F20%2F31b1cf6c-9b38-4826-8885-1a42c718dc31_.webp?alt=media	Smartphone-Xiaomi-Redmi-Note-14-256GB-8GB-RAM-6-67-AMOLED-120Hz-C-mera-108Mp-Verde_1752181186.webp	2	20
97	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F20%2F03892994-24d5-41c7-b77c-c8bca8646ddd_.webp?alt=media	Smartphone-Xiaomi-Redmi-Note-14-256GB-8GB-RAM-6-67-AMOLED-120Hz-C-mera-108Mp-Verde_1752181188.webp	3	20
98	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F21%2F62f9e49f-a7d0-4e28-969f-2d7dacc0e6b9_.jpeg?alt=media	iphone-15-blue-select-202309_AV2.jpeg	0	21
99	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F21%2F93ee2848-600a-4705-ad4a-a377e7c5e658_.jpeg?alt=media	iphone-15-model-unselect-gallery-1-202309.jpeg	1	21
100	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F21%2F037889d9-eb76-4ecd-b998-940a78ef22ed_.jpeg?alt=media	iphone-15-model-unselect-gallery-2-202309.jpeg	2	21
101	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F21%2F46106439-c022-4753-b71d-8c3deee9de0c_.jpeg?alt=media	iphone-compare-iphone-16-202409.jpeg	3	21
102	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F21%2Fb2ced4e1-32d7-4c49-8740-75b6a073dc71_.jpeg?alt=media	iphone-compare-iphone-16-pro-202409.jpeg	4	21
103	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F22%2Fb9f9b634-b51f-4427-a9a4-cc3142d73d49_.webp?alt=media	Smartphone-Samsung-Galaxy-S24-Ultra-5G-256GB-12GB-RAM-C-mera-200MP-Tela-6-8-120Hz-S-Pen-Preto_1751571299.webp	0	22
104	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F22%2Fb9f44771-e3b7-431c-bb7b-d73d1cd9b75f_.webp?alt=media	Smartphone-Samsung-Galaxy-S24-Ultra-5G-256GB-12GB-RAM-C-mera-200MP-Tela-6-8-120Hz-S-Pen-Preto_1751571300.webp	1	22
105	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F22%2F5a9220c6-84be-43ee-9828-df9fe71b3075_.webp?alt=media	Smartphone-Samsung-Galaxy-S24-Ultra-5G-256GB-12GB-RAM-C-mera-200MP-Tela-6-8-120Hz-S-Pen-Preto_1751571301.webp	2	22
106	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F22%2F52243293-5fe8-414f-b84b-b3d23fe3ed53_.webp?alt=media	Smartphone-Samsung-Galaxy-S24-Ultra-5G-256GB-12GB-RAM-C-mera-200MP-Tela-6-8-120Hz-S-Pen-Preto_1751571303.webp	3	22
107	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F22%2F957025cd-9022-4126-b226-953642fdf307_.webp?alt=media	Smartphone-Samsung-Galaxy-S24-Ultra-5G-256GB-12GB-RAM-C-mera-200MP-Tela-6-8-120Hz-S-Pen-Preto_1751571304.webp	4	22
108	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F23%2F74a310ad-4e09-4b1b-afa2-907df63b0ba6_.jpg?alt=media	61Vfhwv+kpL._AC_SX522_.jpg	0	23
109	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F23%2Fce0fa9f3-024f-40f2-8dde-3c93e6f0ef02_.jpg?alt=media	71b7ccyRKzL._AC_SL1200_.jpg	1	23
110	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F23%2Fed5b2bca-c31a-4ee8-8257-b7e848d32e2d_.jpg?alt=media	71vQE6kAJYL.jpg	2	23
111	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F23%2Fd0e8b1ff-419f-4686-bb90-59791d8a4fc6_.jpg?alt=media	616+gFQAU9L._AC_SL1200_.jpg	3	23
112	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F23%2Fa565512d-5046-414a-8dab-87b21d885b66_.jpg?alt=media	713E1KM6QoL._AC_SL1200_.jpg	4	23
113	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F24%2F6af2326d-ca07-4aa3-b876-031085d4c615_.jpg?alt=media	51a1kv0zhyL._AC_SL1000_.jpg	0	24
114	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F24%2Fc9114b0a-9f78-4cf2-9632-b22c50033a64_.jpg?alt=media	61xNEsolidL._AC_SX679_.jpg	1	24
115	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F24%2Fc23ccb8e-5770-49fc-ac26-42bbf9d2cc68_.jpg?alt=media	81ExWjQG-SL._AC_SX569_.jpg	2	24
116	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F24%2F091d918b-e30c-418d-8539-c220bf1cd252_.jpg?alt=media	514PTL1LAAL._AC_SL1000_.jpg	3	24
117	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F25%2F14d369e1-819e-4386-83e8-bbe8f92cf792_.webp?alt=media	Apple-iPhone-14-128GB-Estelar-6-1-12MP-iOS-5G_1749817999.webp	0	25
118	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F25%2F2289a995-9829-4165-bb64-039a84f6f56c_.webp?alt=media	Apple-iPhone-14-128GB-Estelar-6-1-12MP-iOS-5G_1749818004.webp	1	25
119	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F25%2Fd0235356-45f5-4643-b88d-2f58ee6beeb9_.webp?alt=media	Apple-iPhone-14-128GB-Estelar-6-1-12MP-iOS-5G_1749818005.webp	2	25
120	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F25%2Fa22271b3-b83f-467d-8ec5-4f0d91c4f5d3_.webp?alt=media	Apple-iPhone-14-128GB-Estelar-6-1-12MP-iOS-5G_1749818007.webp	3	25
121	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F25%2F331448ab-d173-493a-b505-f49392bc365c_.webp?alt=media	Apple-iPhone-14-128GB-Estelar-6-1-12MP-iOS-5G_1749818008.webp	4	25
122	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F25%2F6717d2b7-7c94-4aa3-ad44-f3ddd1408a2d_.webp?alt=media	Apple-iPhone-14-128GB-Estelar-6-1-12MP-iOS-5G_1749818011.webp	5	25
123	https://firebasestorage.googleapis.com/v0/b/animated-cinema-392321.appspot.com/o/produtos%2F25%2F46e78e26-3ef9-477f-9a21-368d4b2547ca_.webp?alt=media	Apple-iPhone-14-128GB-Estelar-6-1-12MP-iOS-5G_1749818012.webp	6	25
\.


--
-- Data for Name: Produtos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Produtos" ("Id", "Nome", "Slug", "Descricao", "Preco", "CategoriaId", "PrecoAntigo", "Marca", "Quantidade") FROM stdin;
1	Samsung Galaxy S23 Ultra 5G 512GB - Verde	samsung-galaxy-s23-ultra-5g-512gb-verde	O Samsung Galaxy S23 Ultra combina desempenho de alto nÃ­vel com um design sofisticado. Equipado com 512GB de armazenamento interno e 12GB de RAM, Ã© ideal para quem precisa de velocidade e espaÃ§o. Possui cÃ¢mera principal de 200MP com zoom Ã³ptico de 10x, perfeita para fotos com qualidade profissional. Sua tela AMOLED de 6,8" com taxa de atualizaÃ§Ã£o de 120Hz garante uma experiÃªncia fluida e vibrante. Conta com processador Snapdragon 8 Gen 2, bateria de 5000mAh com carregamento rÃ¡pido, suporte a 5G e resistÃªncia Ã  Ã¡gua IP68.	7999.00	5	9499.00	Samsung	13
2	 Cadeira Gamer ThunderX Blaze V2 RGB	cadeira-gamer-thunderx-blaze-v2-rgb	A ThunderX Blaze V2 RGB Ã© a cadeira ideal para quem passa horas jogando ou trabalhando. Com design ergonÃ´mico, apoios ajustÃ¡veis (braÃ§o, altura e inclinaÃ§Ã£o atÃ© 180Â°), estofamento em espuma de alta densidade e revestimento em couro sintÃ©tico premium. Destaque para o sistema de iluminaÃ§Ã£o RGB com controle remoto, que permite personalizar seu setup com estilo. Suporta atÃ© 150kg com base reforÃ§ada em aÃ§o.	1249.00	4	1499.90	ThunderX	12
3	ThunderX3 EC1 RGB Black Edition	thunderx3-ec1-rgb-black-edition	Cadeira gamer com iluminaÃ§Ã£o RGB, encosto reclinÃ¡vel atÃ© 180Â°, almofadas lombar e cervical inclusas. Revestimento em couro sintÃ©tico premium.	1429.90	4	1799.00	ThunderX3	12
4	Cadeira Gamer ThunderX3 BC3 Camo Admiral Azul	cadeira-gamer-thunderx3-bc3-camo-admiral-azul	Com visual camuflado azul marcante, a BC3 Camo Blue da ThunderX3 une robustez e conforto. Feita com estrutura de aÃ§o, assento largo e espuma moldada, ela garante durabilidade e adaptaÃ§Ã£o ao corpo. Os apoios de braÃ§o 2D sÃ£o ajustÃ¡veis em altura e direÃ§Ã£o, enquanto o encosto reclina atÃ© 180Â°. A base metÃ¡lica garante firmeza mesmo para usuÃ¡rios de atÃ© 150kg. Excelente para streamers, gamers competitivos e profissionais que passam muitas horas na frente do PC.	1299.90	4	1499.00	ThunderX3	23
5	Cadeira Gamer ThunderX3 YC3 Preto/Vermelho, YC3 PT/VM 70626	cadeira-gamer-thunderx3-yc3-pretovermelho-yc3-ptvm-70626	A YC3 Red Fury oferece uma experiÃªncia gamer imersiva com visual agressivo em vermelho e preto. Seu estofamento Ã© feito com espuma de alta densidade, revestida em couro sintÃ©tico resistente e de fÃ¡cil limpeza. A estrutura metÃ¡lica interna aumenta a durabilidade e o encosto Ã© reclinÃ¡vel em atÃ© 135Â°. Os apoios de braÃ§o sÃ£o ajustÃ¡veis e as almofadas de suporte lombar e cervical ajudam a manter a postura ideal. Ã“tima para setups pequenos e mÃ©dios que buscam visual forte e conforto duradouro.	1079.90	4	1299.00	ThunderX3	26
6	Cadeira Gamer ThunderX3 TC5 Max Preta	cadeira-gamer-thunderx3-tc5-max-preta	Uma das ediÃ§Ãµes mais premium da marca, a TC5 RGB oferece iluminaÃ§Ã£o RGB completa, com controle via botÃ£o integrado. O modelo traz apoio de pÃ©s retrÃ¡til, encosto com reclinaÃ§Ã£o total, almofadas de apoio inclusas, e acabamento costurado em couro PU de alta qualidade. A espuma de densidade extra garante conforto mesmo apÃ³s vÃ¡rias horas. Ideal para criadores de conteÃºdo e quem quer impressionar com estilo.	1789.90	4	2099.00	ThunderX3	21
7	 DXRacer Formula Series Preta	dxracer-formula-series-preta	A Formula Series Ã© o modelo mais tradicional da DXRacer e continua sendo um dos mais vendidos do mundo. Seu design foi pensado para simular bancos de carro de corrida, com foco na ergonomia. Revestida em couro sintÃ©tico PU, possui almofadas lombar e cervical, apoio de braÃ§o 2D e encosto com reclinaÃ§Ã£o de atÃ© 135Â°. A estrutura interna em aÃ§o reforÃ§ado e a base de nylon suportam usuÃ¡rios de atÃ© 120kg. Ideal para quem quer o selo DXRacer com Ã³timo custo-benefÃ­cio.	1899.90	4	2299.00	DXRacer	8
8	 DXRacer Racing Series Branca e Azul	dxracer-racing-series-branca-e-azul	Inspirada em carros de corrida, a DXRacer Racing Series traz visual esportivo em branco e azul, com costuras elegantes. Ã‰ equipada com apoios de braÃ§o 4D (altura, rotaÃ§Ã£o, profundidade e largura ajustÃ¡veis), encosto reclinÃ¡vel em atÃ© 135Â°, almofadas ajustÃ¡veis e espuma de alta densidade. A base em alumÃ­nio suporta atÃ© 150kg, com rolagem suave. Modelo indicado para setups de alto nÃ­vel e jogadores exigentes.	2099.90	4	2499.00	DXRacer	23
9	cadeira-de-escritorio-dr-office-ergo-pro-cinza	cadeira-de-escritorio-dr-office-ergo-pro-cinza	O visual clean e contemporÃ¢neo da Siggy foi pensado para quem trabalha em Ã¡reas criativas ou tÃ©cnicas. O design nÃ£o Ã© apenas visual; Ã© funcional e eficiente, feita para pessoas que valorizam tanto a estÃ©tica quanto o desempenho\n\n	1829.99	4	0.00	Siggy	3
10	Samsung Odyssey G5 27" 144Hz Curvo QHD	samsung-odyssey-g5-27-144hz-curvo-qhd	O Odyssey G5 Ã© um monitor gamer de alto desempenho com tela curva de 27â€ e resoluÃ§Ã£o QHD (2560x1440). Possui taxa de atualizaÃ§Ã£o de 144Hz, tempo de resposta de 1ms e tecnologia AMD FreeSync Premium, garantindo gameplay fluido e sem tearing. O painel VA oferece alto contraste e imersÃ£o total com curvatura 1000R. Ideal para gamers competitivos e entusiastas.	2089.90	7	2499.00	Samsung	12
11	 Samsung T350 24" Full HD 75Hz	samsung-t350-24-full-hd-75hz	Com design moderno de bordas ultrafinas, o Samsung T350 Ã© um monitor versÃ¡til de 24â€ Full HD. Possui taxa de atualizaÃ§Ã£o de 75Hz, painel IPS para melhores Ã¢ngulos de visÃ£o e AMD FreeSync para maior estabilidade visual. Ideal para quem joga casualmente, trabalha ou estuda com qualidade.\n\n	839.90	7	999.00	Samsung	13
12	Samsung Odyssey Neo G7 32" 165Hz 4K Curvo	samsung-odyssey-neo-g7-32-165hz-4k-curvo	Este Ã© o topo da linha Odyssey. Tela curva de 32" com resoluÃ§Ã£o 4K (UHD), taxa de 165Hz, HDR 600 e tecnologia Quantum Mini LED. Traz visual realista e tempo de resposta de 1ms para mÃ¡xima performance em jogos. Design futurista e ajuste ergonÃ´mico completam a experiÃªncia.	4799.90	7	5999.00	Samsung	23
13	LG UltraGear 24GN60R-B 24" 144Hz	lg-ultragear-24gn60r-b-24-144hz	Com 144Hz e 1ms, o LG UltraGear 24GN60R-B Ã© ideal para jogos rÃ¡pidos como FPS e MOBAs. A tela IPS oferece cores vibrantes e Ã³timos Ã¢ngulos. Com suporte ao FreeSync e compatibilidade com G-Sync, Ã© uma Ã³tima escolha para quem busca desempenho com custo acessÃ­vel.	1249.90	7	1499.00	 LG	12
14	 LG UltraGear 27GP850-B 27" 165Hz QHD	lg-ultragear-27gp850-b-27-165hz-qhd	Monitor premium da linha UltraGear com 27", resoluÃ§Ã£o QHD e taxa de 165Hz (overclock atÃ© 180Hz). Tela IPS com cores reais e HDR10. Ideal para gamers que querem qualidade de imagem e performance extrema. Suporte total ao G-Sync e FreeSync Premium.	2699.90	7	3199.00	LG	21
15	LG 29WP60G-B Ultrawide 29" Full HD IPS	lg-29wp60g-b-ultrawide-29-full-hd-ips	Modelo ultrawide com proporÃ§Ã£o 21:9, ideal para multitarefa e jogos imersivos. Com painel IPS, 75Hz e suporte a FreeSync, oferece fluidez e excelente espaÃ§o de tela para produtividade ou simulaÃ§Ã£o. Tem entrada USB-C e HDMI.	1379.90	7	1599.00	 LG	24
16	AOC Hero 24G2/BK 24" 144Hz IPS	aoc-hero-24g2bk-24-144hz-ips	Um dos modelos mais elogiados do mercado gamer, o AOC Hero 24G2 oferece 144Hz, 1ms, painel IPS e excelente fidelidade de cores. Possui ajuste de altura, FreeSync, G-Sync compatÃ­vel e design com bordas finas. Excelente custo-benefÃ­cio.	1189.90	7	1399.00	AOC	23
17	 AOC Agon AG273FXR 27" 144Hz Rosa	aoc-agon-ag273fxr-27-144hz-rosa	Modelo com visual Ãºnico em branco e rosa, o AG273FXR traz tela de 27", 144Hz, 1ms e painel IPS. Indicado para setups personalizados e gamers que buscam qualidade com estilo. Suporte total a FreeSync e G-Sync.	1799.90	7	2099.00	AOC	34
18	AOC CQ32G3SU/BK â€“ 31,5â€³ QHD (2560Ã—1440), 165â€¯Hz, 1â€¯ms, 1000R	aoc-cq32g3subk-315-qhd-25601440-165-hz-1-ms-1000r	Tela imersiva com curvatura agressiva de 1000R que reduz o cansaÃ§o visual e aumenta a imersÃ£o. Painel VA de alta qualidade, com AMD FreeSync Premium, presets gaming (como crosshair), alto-falantes integrados e ajuste de altura. Ideal para gamers exigentes que buscam performance fluida e visual imersivo	1789.90	7	1989.90	AOC	13
19	Samsung Galaxy S24â€¯FEÂ 5G	samsung-galaxy-s24-fe-5g	VersÃ£o mais acessÃ­vel da linha S24 com chipset Snapdragon/Exynos, tela AMOLED 6,7â€³ 120â€¯Hz, IP68, cÃ¢mera tripla e suporte 5G.	2799.00	5	3499.00	 Samsung	12
20	Smartphone Xiaomi Redmi Note 14 256GB 8GB RAM 6.67" AMOLED 120Hz CÃ¢mera 108Mp - Verde	smartphone-xiaomi-redmi-note-14-256gb-8gb-ram-667-amoled-120hz-camera-108mp-verde	CÃ¢mera de 108MP AI â€“ Fotos detalhadas e com inteligÃªncia artificial para aprimoramento automÃ¡tico.\nTela Corning Gorilla Glass 5 â€“ Maior resistÃªncia contra quedas e arranhÃµes.\nTaxa de AtualizaÃ§Ã£o de 120Hz â€“ Imagens suaves e resposta rÃ¡pida ao toque.\nSensor de ImpressÃ£o Digital na Tela â€“ Mais seguranÃ§a e desbloqueio rÃ¡pido.\nBateria de 5500mAh â€“ Autonomia para o dia inteiro sem preocupaÃ§Ãµes.\nCarregador Turbo de 33W â€“ Recarga rÃ¡pida para mais conveniÃªncia.\nProcessador MediaTek Helio G99-Ultra â€“ Alto desempenho e eficiÃªncia energÃ©tica.\nArmazenamento de 256GB e 8GB RAM â€“ Mais espaÃ§o e fluidez para rodar diversos aplicativos.	1605.00	5	1899.00	Xiaomi 	21
21	 iPhoneÂ 15	iphone-15	 iPhone 15 traz o design mais moderno com bordas arredondadas, Dynamic Island (recorte inteligente no topo), porta USB-C e chip A16 Bionic, mesmo do iPhone 14 Pro. CÃ¢mera principal de 48MP com fotos incrÃ­veis, bateria otimizada e gravaÃ§Ã£o de vÃ­deo cinematogrÃ¡fico. Ã‰ o novo â€œqueridinhoâ€ do pÃºblico Apple em 2024.\nRecomendado para quem quer um iPhone atual com desempenho de Pro, mas preÃ§o mais acessÃ­vel.	4299.00	5	5199.00	Apple	14
22	Samsung Galaxy S24 Ultra â€“ 512GB, Tela 6.8" AMOLED 120Hz, CÃ¢mera 200MP	samsung-galaxy-s24-ultra-512gb-tela-68-amoled-120hz-camera-200mp	O topo da linha S24, o Ultra impressiona com sua tela AMOLED de 6.8" com bordas retas, taxa de atualizaÃ§Ã£o adaptativa (LTPO) de 1 a 120Hz e brilho altÃ­ssimo para uso em qualquer ambiente. Equipado com processador Snapdragon 8 Gen 3, traz performance absurda em jogos e ediÃ§Ã£o de vÃ­deo. Sua cÃ¢mera de 200MP com zoom Ã³ptico de atÃ© 10x Ã© uma das melhores do mercado. Bateria de 5.000mAh com carregamento rÃ¡pido e suporte Ã  S Pen integrada.\nRecomendado para criadores de conteÃºdo, fotÃ³grafos e gamers exigentes.	7899.90	5	8999.00	Samsung	0
23	Xiaomi Poco X6 Pro â€“ 256GB, AMOLED 120Hz, Dimensity 8300 Ultra	xiaomi-poco-x6-pro-256gb-amoled-120hz-dimensity-8300-ultra	Poco X6 Pro traz um dos melhores desempenhos da faixa intermediÃ¡ria, graÃ§as ao chipset Dimensity 8300 Ultra (nÃ­vel flagship). Tela AMOLED de 6.67" com taxa de atualizaÃ§Ã£o de 120Hz e 1.5K de resoluÃ§Ã£o, alÃ©m de cÃ¢mera principal de 64MP com OIS (estabilizaÃ§Ã£o Ã³ptica). Bateria de 5.000mAh com carregamento rÃ¡pido de 67W.\nIndicado para gamers, multitarefa intensa e quem quer desempenho top sem gastar tanto.	2099.00	5	2399.00	Xiaomi	24
24	iPhone 12 â€“ 64GB, Tela Super Retina XDR, Chip A14 Bionic	iphone-12-64gb-tela-super-retina-xdr-chip-a14-bionic	Mesmo apÃ³s alguns anos, o iPhone 12 continua atual com seu design flat, tela OLED com altÃ­ssima definiÃ§Ã£o e chip A14 Bionic, que ainda roda tudo com fluidez. Vem com cÃ¢mera dupla de 12MP com modo noturno, gravaÃ§Ã£o 4K Dolby Vision e Face ID. CompatÃ­vel com o iOS 17 e MagSafe.\nÃ“timo para quem quer entrar no mundo Apple com um modelo sÃ³lido e atualizado.	1877.00	5	2199.00	Apple	23
25	 iPhone 14 â€“ 128GB, Tela OLED 6.1", CÃ¢meras com Action Mode	iphone-14-128gb-tela-oled-61-cameras-com-action-mode	Visual idÃªntico ao iPhone 13, mas com melhorias na cÃ¢mera frontal (agora com autofoco) e sensores mais avanÃ§ados. Chip A15 Bionic com GPU de 5 nÃºcleos (mesmo do 13 Pro), excelente para games e vÃ­deos. Conta com detecÃ§Ã£o de acidente, SOS via satÃ©lite (em regiÃµes compatÃ­veis), e grava vÃ­deos com excelente estabilizaÃ§Ã£o.\nRecomendado para quem quer o melhor custo-benefÃ­cio entre os iPhones mais novos.	3779.00	5	4399.00	Apple	23
\.


--
-- Data for Name: TrocasEmail; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TrocasEmail" ("Id", "EmailAtual", "NovoEmail", "Codigo", "Expiracao", "Utilizado") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Nome", "Email", "Senha", "Telefone", "Ativo", "Role", "Cpf", "DataNascimento", "Genero") FROM stdin;
1	Antonio Filho da ConceiÃ§Ã£o Filho	antoniofilhodaconceicaorozafil@gmail.com	$2a$11$8acLfQzl2RWvytUy8JdJ9OaM8zb7t7toe4ORW/dUo/YnxnKTWkO1C	98984158711	t	admin	10958921342	2006-07-15	M
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250421184316_Inicial	9.0.4
20250423161354_InitialCreate	9.0.4
20250507004453_AddUsersTable	9.0.4
20250512175704_Carrinho	9.0.4
20250516173948_AddCpfGenero_Cadatro	9.0.4
20250516180117_AlterDataNascimentoToDateOnly	9.0.4
20250516180150_AjustaDataNascimentoParaDateOnly	9.0.4
20250520153452_AddPrecoAntigoToProduto	9.0.4
20250601172502_AumentaTamanhoDescricao	9.0.4
20250609173336_AddEnderecoTable	9.0.4
20250611014609_AddEnderecoTable-Idetificacao	9.0.4
20250613005625_AddTrocaEmailTable	9.0.4
20250616184624_AdicionarFavoritos	9.0.4
20250624200902_CriarPedidos	9.0.4
20250624212604_CriarPedidosAtualizandoIndereco	9.0.4
20250624214947_AddEnderecoIdToPedidoNullable	9.0.4
20250703020342_AddMarcaQuantidadeToProduto	9.0.4
20250711181746_AddNovasTabelas	9.0.4
20250711182943_AddNovasTabelass	9.0.4
20250711183209_AddNovasTabela	9.0.4
\.


--
-- Name: Carrinhos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Carrinhos_Id_seq"', 1, false);


--
-- Name: Categorias_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categorias_Id_seq"', 7, true);


--
-- Name: Enderecos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Enderecos_Id_seq"', 1, false);


--
-- Name: Favoritos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Favoritos_Id_seq"', 1, false);


--
-- Name: ItemPedido_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ItemPedido_Id_seq"', 1, false);


--
-- Name: ItensCarrinho_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ItensCarrinho_Id_seq"', 1, false);


--
-- Name: Pedidos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Pedidos_Id_seq"', 1, false);


--
-- Name: ProdutoImagens_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProdutoImagens_Id_seq"', 123, true);


--
-- Name: Produtos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Produtos_Id_seq"', 25, true);


--
-- Name: TrocasEmail_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TrocasEmail_Id_seq"', 1, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- Name: Carrinhos PK_Carrinhos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Carrinhos"
    ADD CONSTRAINT "PK_Carrinhos" PRIMARY KEY ("Id");


--
-- Name: Categorias PK_Categorias; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categorias"
    ADD CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id");


--
-- Name: Enderecos PK_Enderecos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Enderecos"
    ADD CONSTRAINT "PK_Enderecos" PRIMARY KEY ("Id");


--
-- Name: Favoritos PK_Favoritos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favoritos"
    ADD CONSTRAINT "PK_Favoritos" PRIMARY KEY ("Id");


--
-- Name: ItemPedido PK_ItemPedido; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemPedido"
    ADD CONSTRAINT "PK_ItemPedido" PRIMARY KEY ("Id");


--
-- Name: ItensCarrinho PK_ItensCarrinho; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItensCarrinho"
    ADD CONSTRAINT "PK_ItensCarrinho" PRIMARY KEY ("Id");


--
-- Name: Pedidos PK_Pedidos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pedidos"
    ADD CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id");


--
-- Name: ProdutoImagens PK_ProdutoImagens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProdutoImagens"
    ADD CONSTRAINT "PK_ProdutoImagens" PRIMARY KEY ("Id");


--
-- Name: Produtos PK_Produtos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Produtos"
    ADD CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id");


--
-- Name: TrocasEmail PK_TrocasEmail; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TrocasEmail"
    ADD CONSTRAINT "PK_TrocasEmail" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Carrinhos_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Carrinhos_UserId" ON public."Carrinhos" USING btree ("UserId");


--
-- Name: IX_Enderecos_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Enderecos_UserId" ON public."Enderecos" USING btree ("UserId");


--
-- Name: IX_Favoritos_ProdutoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Favoritos_ProdutoId" ON public."Favoritos" USING btree ("ProdutoId");


--
-- Name: IX_Favoritos_UserId_ProdutoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Favoritos_UserId_ProdutoId" ON public."Favoritos" USING btree ("UserId", "ProdutoId");


--
-- Name: IX_ItemPedido_PedidoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ItemPedido_PedidoId" ON public."ItemPedido" USING btree ("PedidoId");


--
-- Name: IX_ItemPedido_ProdutoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ItemPedido_ProdutoId" ON public."ItemPedido" USING btree ("ProdutoId");


--
-- Name: IX_ItensCarrinho_CarrinhoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ItensCarrinho_CarrinhoId" ON public."ItensCarrinho" USING btree ("CarrinhoId");


--
-- Name: IX_ItensCarrinho_ProdutoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ItensCarrinho_ProdutoId" ON public."ItensCarrinho" USING btree ("ProdutoId");


--
-- Name: IX_Pedidos_EnderecoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Pedidos_EnderecoId" ON public."Pedidos" USING btree ("EnderecoId");


--
-- Name: IX_Pedidos_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Pedidos_UserId" ON public."Pedidos" USING btree ("UserId");


--
-- Name: IX_ProdutoImagens_ProdutoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProdutoImagens_ProdutoId" ON public."ProdutoImagens" USING btree ("ProdutoId");


--
-- Name: IX_Produtos_CategoriaId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Produtos_CategoriaId" ON public."Produtos" USING btree ("CategoriaId");


--
-- Name: IX_Produtos_Slug; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Produtos_Slug" ON public."Produtos" USING btree ("Slug");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- Name: Carrinhos FK_Carrinhos_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Carrinhos"
    ADD CONSTRAINT "FK_Carrinhos_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: Enderecos FK_Enderecos_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Enderecos"
    ADD CONSTRAINT "FK_Enderecos_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Favoritos FK_Favoritos_Produtos_ProdutoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favoritos"
    ADD CONSTRAINT "FK_Favoritos_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES public."Produtos"("Id") ON DELETE CASCADE;


--
-- Name: Favoritos FK_Favoritos_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favoritos"
    ADD CONSTRAINT "FK_Favoritos_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: ItemPedido FK_ItemPedido_Pedidos_PedidoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemPedido"
    ADD CONSTRAINT "FK_ItemPedido_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES public."Pedidos"("Id") ON DELETE CASCADE;


--
-- Name: ItemPedido FK_ItemPedido_Produtos_ProdutoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemPedido"
    ADD CONSTRAINT "FK_ItemPedido_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES public."Produtos"("Id") ON DELETE RESTRICT;


--
-- Name: ItensCarrinho FK_ItensCarrinho_Carrinhos_CarrinhoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItensCarrinho"
    ADD CONSTRAINT "FK_ItensCarrinho_Carrinhos_CarrinhoId" FOREIGN KEY ("CarrinhoId") REFERENCES public."Carrinhos"("Id") ON DELETE CASCADE;


--
-- Name: ItensCarrinho FK_ItensCarrinho_Produtos_ProdutoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItensCarrinho"
    ADD CONSTRAINT "FK_ItensCarrinho_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES public."Produtos"("Id") ON DELETE RESTRICT;


--
-- Name: Pedidos FK_Pedidos_Enderecos_EnderecoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pedidos"
    ADD CONSTRAINT "FK_Pedidos_Enderecos_EnderecoId" FOREIGN KEY ("EnderecoId") REFERENCES public."Enderecos"("Id");


--
-- Name: Pedidos FK_Pedidos_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pedidos"
    ADD CONSTRAINT "FK_Pedidos_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: ProdutoImagens FK_ProdutoImagens_Produtos_ProdutoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProdutoImagens"
    ADD CONSTRAINT "FK_ProdutoImagens_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES public."Produtos"("Id") ON DELETE CASCADE;


--
-- Name: Produtos FK_Produtos_Categorias_CategoriaId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Produtos"
    ADD CONSTRAINT "FK_Produtos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES public."Categorias"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

